import Head from "next/head";
import TuitCard from "../components/TuitCard/TuitCard";
import styles from "../styles/Home.module.css";

export default function Home({ tuits }) {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Tiutah</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.container}>
          <section className="section-tuits row justify-content-around">
            {tuits.map((tuit) => (
              // eslint-disable-next-line no-underscore-dangle
              <TuitCard key={tuit._id} tuit={tuit} />
            ))}
          </section>
        </div>
      </div>
    </>
  );
}

export const getServerSideProps = async () => {
  const response = await fetch("https://tiuter.herokuapp.com/tuits/");
  const newTuits = await response.json();

  return {
    props: {
      tuits: await newTuits,
    },
  };
};
