import axios from "axios";
import Head from "next/head";
import { useState } from "react";
import TuitCard from "../components/TuitCard/TuitCard";
import styles from "../styles/Home.module.css";

export default function Home({ tuits }) {
  const [tuitsData, setTuitsData] = useState(tuits);

  const onDelete = async (id) => {
    await axios.delete(`https://tiuter.herokuapp.com/tuits/delete/${id}`);
    const freshTuitsList = tuitsData.filter((freshTuit) => freshTuit.id !== id);
    setTuitsData(freshTuitsList);
  };

  const clickLike = async (tuit) => {
    await axios.patch(`https://tiuter.herokuapp.com/tuits/patch`, {
      id: tuit.id,
    });

    const newTuitData = tuitsData.map((tuitData) => {
      if (tuit.id === tuitData.id) {
        tuitData.likes += 1;
        return { ...tuitData };
      }
      return tuitData;
    });

    setTuitsData(newTuitData);
  };
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Tiutah</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.container}>
          <section className="section-tuits row justify-content-around">
            {tuitsData
              .sort((a, b) => {
                const c = new Date(a.date);
                const d = new Date(b.date);
                return d - c;
              })
              .map((tuit) => (
                // eslint-disable-next-line no-underscore-dangle
                <TuitCard
                  key={tuit.id}
                  tuit={tuit}
                  onDelete={onDelete}
                  clickLike={clickLike}
                />
              ))}
          </section>
        </div>
      </div>
    </>
  );
}

export const getServerSideProps = async () => {
  const response = await fetch("https://tiuter.herokuapp.com/tuits/");
  const newTuits = await response.json();

  return {
    props: {
      tuits: await newTuits,
    },
  };
};
